### ISSUE TITLE
mac support?

### ISSUE THREAD

**Issue by barolo** [39aldo39/libdecsync#8]
After trying to load it now [via radicale-decync] I just get:
`[3226] [CRITICAL] An exception occurred during server startup: Failed to load storage module 'radicale_storage_decsync': libdecsync: Operating system 'Darwin' not supported`

**Comment by 39aldo39** [comment]
Mac was not supported as I don't have a mac but I have added it now! I still can't test it myself, but according to the GitHub Actions it should work!

**Comment by barolo** [comment]
> Mac was not supported as I don't have a mac but I have added it now! I still can't test it myself, but according to the GitHub Actions it should work!

It works! Thank you so much.
